#include "token.h"

const char *token_type_name(TokenType type)
{
  switch (type)
  {
  case TOKEN_INT:
    return "INT";
  case TOKEN_FLOAT:
    return "FLOAT";
  case TOKEN_STRING:
    return "STRING";
  case TOKEN_IDENTIFIER:
    return "IDENTIFIER";
  case TOKEN_FUNC:
    return "FUNC";
  case TOKEN_END:
    return "END";
  case TOKEN_RETURN:
    return "RETURN";
  case TOKEN_CONST:
    return "CONST";
  case TOKEN_IF:
    return "IF";
  case TOKEN_ELSE:
    return "ELSE";
  case TOKEN_TRUE:
    return "TRUE";
  case TOKEN_FALSE:
    return "FALSE";
  case TOKEN_NEW:
    return "NEW";
  case TOKEN_THIS:
    return "THIS";
  case TOKEN_NAMESPACE:
    return "NAMESPACE";
  case TOKEN_IMPORT:
    return "IMPORT";
  case TOKEN_FROM:
    return "FROM";
  case TOKEN_CLASS:
    return "CLASS";
  case TOKEN_INTERFACE:
    return "INTERFACE";
  case TOKEN_ENUM:
    return "ENUM";
  case TOKEN_TRAIT:
    return "TRAIT";
  case TOKEN_USE:
    return "USE";
  case TOKEN_IMPLEMENTS:
    return "IMPLEMENTS";
  case TOKEN_EXTENDS:
    return "EXTENDS";
  case TOKEN_CONSTRUCT:
    return "CONSTRUCT";
  case TOKEN_PUBLIC:
    return "PUBLIC";
  case TOKEN_PRIVATE:
    return "PRIVATE";
  case TOKEN_PROTECTED:
    return "PROTECTED";
  case TOKEN_READONLY:
    return "READONLY";
  case TOKEN_STATIC:
    return "STATIC";
  case TOKEN_FOREACH:
    return "FOREACH";
  case TOKEN_AS:
    return "AS";
  case TOKEN_FOR:
    return "FOR";
  case TOKEN_IN:
    return "IN";
  case TOKEN_WHILE:
    return "WHILE";
  case TOKEN_PAGE:
    return "PAGE";
  case TOKEN_COMPONENT:
    return "COMPONENT";
  case TOKEN_STATE:
    return "STATE";
  case TOKEN_ACTION:
    return "ACTION";
  case TOKEN_VIEW:
    return "VIEW";
  case TOKEN_ROUTE:
    return "ROUTE";
  case TOKEN_GROUP:
    return "GROUP";
  case TOKEN_MIDDLEWARE:
    return "MIDDLEWARE";
  case TOKEN_APP:
    return "APP";
  case TOKEN_TYPE_INT:
    return "TYPE_INT";
  case TOKEN_TYPE_FLOAT:
    return "TYPE_FLOAT";
  case TOKEN_TYPE_STRING:
    return "TYPE_STRING";
  case TOKEN_TYPE_BOOL:
    return "TYPE_BOOL";
  case TOKEN_TYPE_OBJECT:
    return "TYPE_OBJECT";
  case TOKEN_TYPE_ARRAY:
    return "TYPE_ARRAY";
  case TOKEN_TYPE_NUMERIC:
    return "TYPE_NUMERIC";
  case TOKEN_COLON:
    return "COLON";
  case TOKEN_EQUALS:
    return "EQUALS";
  case TOKEN_PLUS:
    return "PLUS";
  case TOKEN_MINUS:
    return "MINUS";
  case TOKEN_STAR:
    return "STAR";
  case TOKEN_SLASH:
    return "SLASH";
  case TOKEN_LPAREN:
    return "LPAREN";
  case TOKEN_RPAREN:
    return "RPAREN";
  case TOKEN_LBRACE:
    return "LBRACE";
  case TOKEN_RBRACE:
    return "RBRACE";
  case TOKEN_LBRACKET:
    return "LBRACKET";
  case TOKEN_RBRACKET:
    return "RBRACKET";
  case TOKEN_LESS:
    return "LESS";
  case TOKEN_GREATER:
    return "GREATER";
  case TOKEN_PIPE:
    return "PIPE";
  case TOKEN_COMMA:
    return "COMMA";
  case TOKEN_DOT:
    return "DOT";
  case TOKEN_BANG:
    return "BANG";
  case TOKEN_QUESTION:
    return "QUESTION";
  case TOKEN_ARROW:
    return "ARROW";
  case TOKEN_FAT_ARROW:
    return "FAT_ARROW";
  case TOKEN_EQ_EQ:
    return "EQ_EQ";
  case TOKEN_BANG_EQ:
    return "BANG_EQ";
  case TOKEN_LESS_EQ:
    return "LESS_EQ";
  case TOKEN_GREATER_EQ:
    return "GREATER_EQ";
  case TOKEN_AND:
    return "AND";
  case TOKEN_OR:
    return "OR";
  case TOKEN_PLUS_PLUS:
    return "PLUS_PLUS";
  case TOKEN_MINUS_MINUS:
    return "MINUS_MINUS";
  case TOKEN_NEWLINE:
    return "NEWLINE";
  case TOKEN_EOF:
    return "EOF";
  case TOKEN_ERROR:
    return "ERROR";
  default:
    return "UNKNOWN";
  }
}